### ISSUE TITLE
doesn't connect

### ISSUE THREAD

**Issue by iain17** [nickyhuyskens/SwiftCocoaAsyncSocketTutorial#1]
It doesn't seem to ever connect. Does this example actually work?

**Comment by iain17** [comment]
never mind, it seems to be CocoaAsyncSocket https://github.com/robbiehanson/CocoaAsyncSocket/issues/246

**Comment by nickyhuyskens** [comment]
This was tested and worked! 
If you get this problem again, you might try another network? Maybe yours is secured so that devices cannot connect to each other? (Usualy in schools)

**Comment by nickyhuyskens** [comment]
In the link you provided, Someone gave this answer:
"In the original post, there's nothing else keeping a strong reference to the socket, so it gets deallocated by the end of viewDidLoad()."
This might also be your problem and was also described in my tutorial.
Can I close this issue?

**Comment by iain17** [comment]
Worked? So I assume you haven't tried recently? Can't be my nework as it connects locally to 127.0.0.1 remember. Plus it isn't connecting with a direct clone of your repo. I did indeed read that reply but doesn't seem to be the problem right?

From my investigation the server part doesn't even bind to a port. But maybe you can tell me otherwise

**Comment by nickyhuyskens** [comment]
Specially for you, I did test it again right now and this was my output:

published succesfully on port 52594 / domain: local. / _Tutorial._tcp. / SwiftTutorial
Did connect with service
Socket accepted
Socket connected to host
Test packet sent
Header received with bodylength: 316
Person received, name: Nicky age: 20

So there is no problem whatsoever in the code.

Have you tried publishing the service and finding it with the app "Discovery" from the App Store? There you can see if your service is published or not on the network.
You should also get the message:
published succesfully on port xxxxx / domain: local. / _Tutorial._tcp. / SwiftTutorial
when starting your project

**Comment by iain17** [comment]
The build target seems to be a apple tv one so I don't really know he'd be able to get the "Discovery" app running on it.

Here is a screenshot of me cloning the repo, doing a pod install and then instantly opening the workspace and running it.
http://puu.sh/nXur5/5613fafb04.png

I've spent hours trying to figure it out. Completely lost hope that it was my mistake somewhere when I saw a basic swift test not even working: https://github.com/robbiehanson/CocoaAsyncSocket/issues/415

Are you running on the latest swift 2.2? It just seem from my point of view that the server delegate for a new socket connection never gets fired. I'm just curious as to what I could possibly be missing. Like any indication at all would help

**Comment by nickyhuyskens** [comment]
Discovery should be installed on your iPhone / iPad just to check if you can find it.
I made this using swift 2.1
Its weird that it works for me and not for you, But I see in your screenshot that the service is published. So if you cant find it with Discovery, it might be because you don't have an exisiting reference to the object

**Comment by iain17** [comment]
Interesting. Just gave it another attempt and initialized class that implemented GCDAsyncSocketDelegate from a viewController instead of the appDeletegate. Seems to work alright then. Thanks for your help anyways.
