### ISSUE TITLE
Service Response

### ISSUE THREAD

**Issue by TranMaxime** [nickyhuyskens/SwiftCocoaAsyncSocketTutorial#2]
Hello,
This was a great tutorial, thank you.
I wanted to know how the server could responde to a client who sent him a Person (Per example the server would send something like "Here is a cheatCode: XXXXX !!!" by socket and the client receive the encoded message then decode it)

**Comment by nickyhuyskens** [comment]
First of all, you should create a new class like "StringPacket" or something like that, also add this to the enum of objecttype.
Then in the packet handler, if the server receives a packet of Persontype, you can make it respond using the StringPacket you created.

The StringPacket should just hold 1 variable named String. It's actually exactly the same as the person object but without the age.

You could also do the same without creating a separate class, but just converting it directly to a String in the PacketHandler, but I do think that the way I described is easier to maintain in code :p 

I hope this helps! if you need any more help with this, just ask!

**Comment by TranMaxime** [comment]
Hi, Thank for the answer
My question was probably poorly stated. I was actually wondering how you could answer to a particular Client who sent you something (Maybe a delegate function or something i didnt find) 
Because you are using "Socket.writeData(..)" to send item from client to server. I was wondering if the server had to use the same function to send to the Client. In this case, will it not send data to EVERY client? Or there is something to identifie and send to a specific client?
Same thing for the Client who receive the data. Will he uses the delegate socket didReadData?

**Comment by nickyhuyskens** [comment]
Ow sorry for misunderstanding your question. Yes you should create a very similar function in your PersonService class for that but in this example there is no support for multiple clients.
I think this should be possible by keeping an array of sockets for every connected client and adding an Identifier for every client to every packet but I haven't tried it myself yet.
I hope this was enough for you to continue?

**Comment by TranMaxime** [comment]
Yes, I know what i can test now.
If my tests work, I will close this subject
Thanks for your help.

**Comment by TranMaxime** [comment]
I just finished my test and it worked well.
But something still bothering me.

In this part of the code:

> func socket(sock: GCDAsyncSocket!, didReadData data: NSData!, withTag tag: Int) {
>         if tag == 1 {
>             var bodyLength: Int16 = 0
>             data.getBytes(&bodyLength, length: sizeof(Int16))
>             print("Header received with bodylength: (bodyLength)")
>             socket.readDataToLength(UInt(bodyLength), withTimeout: -1, tag: 2)
>         } else if tag == 2 {
>             let packet = NSKeyedUnarchiver.unarchiveObjectWithData(data) as! Packet
>             PacketHandler.HandlePacket(packet)
>             socket.readDataToLength(UInt(sizeof(Int16)), withTimeout: -1, tag: 1)
>         }
>     }

I was wondering why the code below launch the delegate methode didReadData but not the same code with "tag: 1" in the ELSE part.

> socket.readDataToLength(UInt(bodyLength), withTimeout: -1, tag: 2)

**Comment by nickyhuyskens** [comment]
That is amazing! I'm glad it worked out!
I'm not quite sure if I understand your question, but tag 1 should not be executed in the else part.
The way the tags work here is:
1 = Header
2 = Body
We always start listening for Headers, therefore we listen for tag 1. All headers have a fixed length, so that way, the receiver knows how long to read before converting it to an object.
We use the header for sending the length of the body.
Therefore we start listening for tag 2 with the length that the header provided at the end of the "if tag==1" part.
So in tag 1, only the first part of the sent data will be handled, in tag 2, the packet will be extracted which contains the object/string/etc...
I hope this answers your question? if not, could you please explain more in detail what's bothering you?

**Comment by TranMaxime** [comment]
I wanted to know if the function below do launch the delegate function Socket( DidReadData)

> socket.readDataToLength(..)

If it is so, i was wondering why in the "else if tag == 2" part the 

> socket.readDataToLength(UInt(sizeof(Int16)), withTimeout: -1, tag: 1)

did not call the "if tag == 1" part and then make some infinite loop. Does it wait the client to use 

> socket.writeData()

function?

By the way, I had another question about the client ReadData part.
I did use 

> socket.readDataToLength(UInt(sizeof(Int16)), withTimeout: -1, tag: 5)

to read data coming from server. I called it in didConnectToHost delegate function:

> func socket(sock: GCDAsyncSocket!, didConnectToHost host: String!, port: UInt16) {
>         let person = Person(name: "Nicky", age: 20)
>         let personPacket = PersonPacket(person: person)
>         let packet = Packet(objectType: ObjectType.Personpacket, object: personPacket)
>         sendPacket(packet)
>         print("Test packet sent")
>         socket.readDataToLength(UInt(sizeof(Int16)), withTimeout: -1, tag: 5)
>     }

Is it a good place to do it?

Sorry for all those weird questions

**Comment by nickyhuyskens** [comment]
No it doesn't call the delegate function automatically, it waits for the other side to send a message before calling it, that's why it's called "didReadData" (notice that it is past tense).
And for the second question, yes that is a possible place to do it, but I'd recommend moving that line to above the "let person = ...". That way, if the server responds to the packet you send, you can be sure that the client is already ready to accept incoming messages.

**Comment by TranMaxime** [comment]
Right, thank for the answer, i should be able to continue by myself now

**Comment by TranMaxime** [comment]
Hi
I am trying to communicate between a iOS device and a iOS simulator.
One launch the PersonService and the other one the PersoneServiceBrowser via button. They are both in the same wifi.

My problem is that it doesn't appear to communicate between them (no connexion appear in debuggor).
By the way, if I put client and server in the device, it works well but when its separated it doesn't work anymore.

Do you have any solution for this problem?

**Comment by nickyhuyskens** [comment]
on your iOS device, download the free app called Discovery.
In this app, you can see if the service has been published on the local network.

**Comment by TranMaxime** [comment]
I installed 

> https://itunes.apple.com/fr/app/discovery/id954950375?mt=8&ign-mpt=uo%3D4

(not sure if it's the right app)
I launched the AsyncSocketBonjour App and opened the service and serviceBrowser on the iOS device, but nothing is shown in Discovery (white tableView). But the AsyncSocketBonjour App work well (if the service and serviceBrowser are launch in the same device).
I also tried to launch the services from my Mac but nothing on the Discovery App either on the iOS

**Comment by TranMaxime** [comment]
I also tried to launch the app on 2 different MAC, one would simulate the server and the other one the client, both in the simulator but the result is the same as if i used the iOS device and a simulator.

**Comment by nickyhuyskens** [comment]
Sorry that's the wrong app
https://itunes.apple.com/be/app/discovery-bonjour-browser/id305441017?mt=8
And what do you mean with AsyncSocketBonjour App?

**Comment by TranMaxime** [comment]
Thanks for the link, ill try it
By AsyncSocketBonjour App I mean the tutorial app (with my modification)

**Comment by TranMaxime** [comment]
When I open the server on the phone, i can detect 

> _tutorial._tcp.

when im trying to tip in, it shows a "scanning..." loop infinitly
But when I launch it from my mac, it doesnt detect it.

Now that i can see the services published in my local network I have another question:
I tried different service type name for the test and they were all launched from my iOS device and now, i'm seeing multiple service (tutorial._tcp, tutorial2._tcp, tutorial3._tcp ...). Is it because it keep it in memory? Im also certain that I closed those service with a button that called this delegate in the server class:

> func socketDidDisconnect(sock: GCDAsyncSocket!, withError err: NSError!) {
>         guard let sock = sock else {
>             return
>         }
>         if (socket == sock) {
>             print("(SERVER) Socket server disconnected")
>             socket.delegate = nil
>             socket = nil
>             service?.delegate = nil
>             service = nil
>         }
>     }

**Comment by TranMaxime** [comment]
I just made the same test with Bonjour Browser on mac and it shows me:
 tutorial._tcp. -> SwiftTutorial -> ipadress and other thing

I am actually working behind a proxy, could it be the problem?

**Comment by TranMaxime** [comment]
I just tried to open 2 simulators on my Mac and they were able to communicate together (Same test as if it were one simulator and a iOS device).

And tried it with 2 iOS device but they couldn't detect each other service.

Did the communication work for you when you used two devices?

**Comment by nickyhuyskens** [comment]
This seems like a problem in your network. Either a firewall is blocking the connection or both devices that you're trying to use are not on the same subnetwork.
I used a combination of Apple TV and iOS device, 
Apple TV and iOS simulator and
Apple TV simulator and iOS device
And all of them worked!
and because you can't find the service using the discovery app when you are running the app from your pc, makes me think that that device is not on the same subnetwork. Are both devices connected using Wi-Fi?
My guess would be that you have an internet cable to your pc and wifi for your phone?

**Comment by TranMaxime** [comment]
I'm not expert with network but it looks like they have the same sub network 255.255.254.0 and they are both using wifi

> http://image.noelshack.com/fichiers/2016/21/1464250806-network.png

**Comment by nickyhuyskens** [comment]
And is your pc on the same network? Are you in a school or a business? because they might block connections between devices on the network.

**Comment by TranMaxime** [comment]
business network and yes it's the same network.
Also tried with two iOS devices and the same problem remain.

**Comment by nickyhuyskens** [comment]
Can you try it on a separate network? maybe a home network or using your phone as a personal hotspot and connect with your pc to it?

**Comment by TranMaxime** [comment]
I will give it a try

**Comment by TranMaxime** [comment]
Hi, I just tried it with a home network and it did work well. I guess my business network is blocking the communication. Do you think there is a way to make it works there?

**Comment by nickyhuyskens** [comment]
I have no idea about that! Maybe you can ask the network manager?

**Comment by TranMaxime** [comment]
Thanks for your help, I am gonna close this topic.
